on:
  push:
    branches:
    - main
    - release/*

jobs:
 lint:
    runs-on: ubuntu-24.04
    steps:
        - run: sudo apt -y update && sudo apt -y install eslint
        - uses: actions/checkout@v6
        - run: env
        - run: |
           cd $GITHUB_WORKSPACE &&
           eslint --init
           for jsfile in $(find . -name '*.json'); do \
             eslint $jsfile 
           done

        
