on:
  push:
    branches:
    - main
    - release/*

jobs:
 lint:
    runs-on: ubuntu-24.04
    steps:
        - run: apt -y update && apt -y install eslint
        - uses: actions/checkout@v6
        - run: env

        
