on:
  push:
    branches:
        - all
  workflow_dispatch:

jobs:
 lint:
    runs-on: ubuntu-24.04
    steps:
        - run: sudo apt -y update && sudo apt -y install eslint npm
        - uses: actions/checkout@v6
        - run: env
        - run: |
           cd $GITHUB_WORKSPACE &&
           npm install inquirer
           eslint --init
           for jsfile in $(find . -name '*.json'); do \
             eslint $jsfile 
           done

        
